
import EmojiItem from './EmojiItem'


export const EmojiList: Array<EmojiItem> = [
  {
    icon: '😊',
    text: '高兴',
    emojiOrder: 0
  },
  {
    icon: '😎',
    text: '装酷',
    emojiOrder: 1
  },
  {
    icon: '😁',
    text: '呲牙',
    emojiOrder: 2
  },
  {
    icon: '😘',
    text: '爱你',
    emojiOrder: 3
  },
  {
    icon: '😂',
    text: '笑哭',
    emojiOrder: 4
  },
  {
    icon: '😒',
    text: '鄙视',
    emojiOrder: 5
  },
  {
    icon: '🤣',
    text: '仰笑',
    emojiOrder: 6
  },
  {
    icon: '👍',
    text: '很棒',
    emojiOrder: 7
  },
  {
    icon: '😍',
    text: '欣喜',
    emojiOrder: 8
  },
  {
    icon: '😢',
    text: '悲伤',
    emojiOrder: 9
  },
  {
    icon: '🤔',
    text: '思考',
    emojiOrder: 10
  },
  {
    icon: '😶‍🌫️',
    text: '羊毛',
    emojiOrder: 11
  },
  {
    icon: '😫',
    text: '尴尬',
    emojiOrder: 12
  },
  {
    icon: '😋',
    text: '好吃',
    emojiOrder: 13
  },
  {
    icon: '😴',
    text: '睡觉',
    emojiOrder: 14
  },
  {
    icon: '🤩',
    text: '星眼',
    emojiOrder: 15
  },

]